dependencies:
- name: rabbitmq
  condition: rabbitmq.enabled
  version: 8.x.x
  repository: https://charts.bitnami.com/bitnami
- name: postgresql-ha
  condition: postgresql-ha.enabled
  version: 8.2.x
  repository: https://charts.bitnami.com/bitnami
- name: airflow 
  condition: airflow.enabled
  repository: https://airflow.apache.org
  version: 1.6.x