global:
  tag: "latest"

dashboard:
  service:
    type: ClusterIP
    port: 80

  image:
    repository: ghcr.io/catenax-ng/product-vas-fraud-dashboard
    tag: main
    pullPolicy: Always
  replicaCount: 1
  registrySecret: "catenax"
  apiHost: api.fraud-dashboard.dev.demo.catena-x.net
  apiPort: 8080

  ingress:
    enabled: true
    path: "/"
    service:
      port: http
    annotations: 
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
    
    hosts:
    - name: fraud-dashboard.dev.demo.catena-x.net
      tls: true 
      tlsSecret: tls-secret

  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false


api:   
  replicaCount: 1
  registrySecret: "catenax"
  image:
    repository: ghcr.io/catenax-ng/product-vas-fraud-api
    tag: main
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: true
    path: "/"
    service:
      port: 8080
    certManager: false
    annotations: 
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
    paths: /
    hosts:
    - name: api-fraud-dashboard.dev.demo.catena-x.net
      tls: true 
      tlsSecret: tls-secret

  reactAppEnvironment:
  db:
    host: "product-value-added-service-postgresql-ha-postgresql-headless"
    port: 5432
    # -> secret
 

  dashboardUrl: https://fraud-dashboard.dev.demo.catena-x.net
  keycloak:
    authUrl: "https://catenaxintakssrv.germanywestcentral.cloudapp.azure.com/iamcentralidp/auth/realms/CX-Central/protocol/openid-connect/auth"
    clientResource: "catenax-api"
    clientRole: "realm:default-roles-catenax"
    realm: "catenax"
  # -> secret
  
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true


rabbitmq:
  enabled: true
  replicaCount: 1
  auth:
    erlangCookie: <path:value-added-service/data/dev/rmq#erlangCookie>
    username: <path:value-added-service/data/dev/rmq#username>
    password: <path:value-added-service/data/dev/rmq#password>
  plugins: "rabbitmq_management rabbitmq_peer_discovery_k8s"

  extraSecrets:
    load-definition:
      load_definition.json: |
        {
          "queues": [
          {
            "name": "catenax-fraud-sync-test",
            "vhost": "/",
            "durable": true,
            "auto_delete": false,
            "arguments": {}
          }],
          "vhosts": [
          {
            "name": "/"
          }],
          "permissions":[
          { 
            "user": "cxadmin", "vhost": "/", "configure": ".*", "write": ".*", "read": ".*" }
          ],
        }
        
  loadDefinition:
    enabled: true
    existingSecret: load-definition
  extraConfiguration: |
    load_definitions = /app/load_definition.json

  ingress:
    enabled: false
    path: /

    pathType: ImplementationSpecific
    hostname: rabbitmq.catenax-cdq.com
    annotations: 
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      nginx/client_max_body_size: 10m
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "4000"
      nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "4000"
      nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "20"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "4000"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "4000"
    tls: true
    
postgresql-ha:
  
  enabled: true
  clusterDomain: cluster.local
  serviceAccount:
    enabled: false
  
  postgresql:
    username: dashboard
    password: <path:value-added-service/data/dev/postgresql#password>
    repmgrPassword: <path:value-added-service/data/dev/postgresql#repmgrPassword>
    database: dashboard
    replicaCount: 2 
    updateStrategyType: RollingUpdate    
    securityContext:
      enabled: true
      fsGroup: 1001   
  
    pdb:
      create: false
      minAvailable: 1
  
  postgresqlImage:
    registry: docker.io
    repository: bitnami/postgresql-repmgr
    tag: 11.15.0-debian-10-r44
    debug: false

  pgpool:
    adminPassword: <path:value-added-service/data/dev/postgresql#password>
    srCheckDatabase: postgres
    replicaCount: 1
    securityContext:
      enabled: true
      fsGroup: 1001

  pgpoolImage:
    registry: docker.io
    repository: bitnami/pgpool
    tag: 4.3.1-debian-10-r38
    pullPolicy: IfNotPresent
    debug: false
  
  volumePermissionsImage:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10-r378
    pullPolicy: Always  
  
  metricsImage:
    registry: docker.io
    repository: bitnami/postgres-exporter
    tag: 0.10.1-debian-10-r66
    pullPolicy: IfNotPresent
    debug: false 
  
  persistence:
    enabled: true    
    accessMode: ReadWriteMany
    size: 8Gi

airflow:
  enabled: true
  extraPipPackages:
  - apache-airflow[sentry]
  fernetKey: <path:value-added-service/data/dev/airflow#fernetKey>
  image:
    gid: 0
    pullPolicy: IfNotPresent
    repository: apache/airflow
    tag: 2.1.4-python3.8
    uid: 50000
  images: 
    migrationsWaitTimeout: 600
  
  createUserJob:
    useHelmHooks: false

  migrateDatabaseJob:
    useHelmHooks: false

  
  webserverSecretKey: <path:value-added-service/data/dev/airflow#webserverSecretKey>
  dags:
    gitSync:
      enabled: true
      branch: main
      rev: HEAD
      depth: 1
      maxFailures: 5
      credentialsSecret: git-credentials
      repo: https://github.com/catenax-ng/product-vas-fraud-dags.git
      subPath: /opt/airflow/dags

    persistence:
      accessMode: ReadOnlyMany
      enabled: false
      size: 1Gi
    

  replicas: 1
  webserver:
    defaultUser:
      enabled: true
      role: Admin
      username: <path:value-added-service/data/dev/airflow#username>
      email: <path:value-added-service/data/dev/airflow#email>
      firstName: user
      lastName: user
      password: <path:value-added-service/data/dev/airflow#password>

  ingress:
    apiVersion: networking.k8s.io/v1
    enabled: true
    flower:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hosts:
      - name: flower-fraud-dashboard.dev.demo.catena-x.net
        
      tls:
        enabled: true
        secretName: tls-secret
    web:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      
      hosts:
      - name: airflow-fraud-dashboard.dev.demo.catena-x.net
        
      tls:
        enabled: true
        secretName: tls-secret
  logs:    
    persistence:      
      enabled: false
      size: 1Gi
      
  pgbouncer:
    enabled: true
    serviceAccount:
      create: false
  postgresql:
    enabled: true
    master:
      
      podAnnotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

    database: airflow
    postgresPassword: <path:value-added-service/data/dev/airflow#pgpassword>
    username: postgres     
    

  redis:
    enabled: true
    password: <path:value-added-service/data/dev/airflow#password>
  

fraudcase:
  replicaCount: 1
  image:
    repository: ghcr.io/catenax-ng/product-vas-fraud-workers
    tag: main

  rmqUrl: <path:value-added-service/data/dev/worker#rmqUrl>
  rmqQueueName: <path:value-added-service/data/dev/worker#rmqQueueName>
  sentryDsn: <path:value-added-service/data/dev/worker#sentryDsn>

  catenaxApiUrl: <path:value-added-service/data/dev/worker#catenaxApiUrl>
  catenaxApiKey: <path:value-added-service/data/dev/worker#catenaxApiKey>
  
  cdqApiUrl: <path:value-added-service/data/dev/worker#cdqApiUrl>
  cdqApiKey: <path:value-added-service/data/dev/worker#cdqApiKey>

  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true