apiVersion: v1
appVersion: "1.0"
description: A Helm chart for catenax dashboard stack
name: dashboard
version: 0.2.1

dependencies:
- name: rabbitmq
  condition: rabbitmq.enabled
  version: 8.x.x
  repository: https://charts.bitnami.com/bitnami
- name: postgresql-ha
  condition: postgresql-ha.enabled
  version: 8.2.x
  repository: https://charts.bitnami.com/bitnami
- name: airflow 
  condition: airflow.enabled
  repository: https://airflow-helm.github.io/charts
  version: 8.6.1