apiVersion: v1
kind: Secret
metadata:
  name: fraud-dashboard
type: Opaque
stringData:
  api-db-user: {{ .Values.api.db.user | quote }}
  api-db-pwd: {{ .Values.api.db.pwd | quote }}
  api-db-name: {{ .Values.api.db.name | quote }}
  sentry-dsn: {{ .Values.api.sentryDsn | quote }}
  cdq-key: {{ .Values.api.cdqKey | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
stringData:  
  GIT_SYNC_USERNAME: {{ .Values.airflow.gitUsers.username | quote }}
  GIT_SYNC_PASSWORD: {{ .Values.airflow.gitUsers.password | quote }}