apiVersion: v1
kind: Secret
metadata:
  name: fraud-dashboard
type: Opaque
stringData:
  api-db-user: <path:value-added-service/dev/api#dbuser>
  api-db-pwd: <path:value-added-service/dev/api#dbpassword>
  api-db-name: <path:value-added-service/dev/api#dbname>
  sentry-dsn: <path:value-added-service/dev/api#sentryDsn>
  cdq-key:  <path:value-added-service/dev/api#cdqKey>

  